version: '2'
services:
  little-doctor-server:
    build: ./little-server
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
  little-doctor-client:
    build: ./little-client
    expose:
      - 8080
      - 22
    entrypoint: ["/app/main"]
    depends_on:
      - "little-doctor-server"
