version: '2'
services:
  little-doctor-redis:
    build: ./little-redis
    entrypoint: ["/usr/bin/redis-server","/etc/redis.conf"]
    expose:
      - 6379
  little-doctor-server:
    build: ./little-server
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
    depends_on:
      - "little-doctor-redis"
    links:
      - "little-doctor-redis:redserver"
  little-doctor-client:
    build: ./little-client
    expose:
      - 8080
      - 22
    entrypoint: "/tmp/launcher.sh"
    links:
      - "little-doctor-redis:redserver"
    depends_on:
      - "little-doctor-redis"
  little-doctor-client-centos:
    build: ./little-client-centos
    expose:
      - 8080
      - 22
    entrypoint: "/tmp/launcher.sh"
    links:
      - "little-doctor-redis:redserver"
    depends_on:
      - "little-doctor-redis"

